name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Clone workflows-openapi
        run: |
          git clone https://github.com/zixiCat/workflows-openapi.git

      - name: Test dir
        run: |
          ls
          cd /home/runner/work/k8s-service/k8s-service/workflows-openapi/src/main/resources/templates/JavaSpring
          ls
          cd /home/runner/work/k8s-service/k8s-service/workflows-openapi/src/main/resources/templates
          ls

      - name: Build and install workflows-openapi
        run: |
          chmod +x ./workflows-openapi/mvnw
          cd workflows-openapi
          pwd
          ls
          ./mvnw clean install

      - name: Build with Maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/k8s-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-service:latest
